[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "wscat-rs"
version = "0.1.0"

[[bin]]
name = "wscat-rs"
path = "src/main.rs"

[dependencies]
clap = "1.5.3"
rl-sys = "0.4.1"
websocket = "0.14.0"
