[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "wscat clone in rust"
homepage = "https://github.com/hwchen/manx-rs"
repository = "https://github.com/hwchen/manx-rs"
keywords = ["websocket", "wscat", "netcat", "cli"]
license = "MIT OR Apache-2.0"
edition = "2018"
name = "manx"
version = "0.3.0"


[[bin]]
name = "manx"
path = "src/main.rs"

[dependencies]
ansi_term = "0.12.1"
clap = "2.33.0"
url = "2.1.1"
anyhow = "1.0.28"
smol = "0.1.4"
async-tungstenite = "0.4.2"
futures = "0.3.4"
piper = "0.1.1"
linefeed = "0.6.0"
