[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "wscat clone in rust"
name = "manx-rs"
version = "0.2.0"

[[bin]]
name = "manx"
path = "src/main.rs"

[dependencies]
ansi_term = "0.7.1"
clap = "1.5.3"
hyper = "0.7.2"
rl-sys = "0.4.1"
url = "0.5.2"
websocket = "0.14.0"
